#+BRAIN_CHILDREN: smorgasbord-README

#+BRAIN_PARENTS: 8bdeea8f-7af3-413e-aee3-9779166bda00

#+TODO: TODO STARTED | WORKING
#+TODO: | TESTED
#+STARTUP: indent

* structure
** browser state anatomy
*** set of tabs on open windows
**** WORKING url
CLOSED: [2020-02-15 Sat 16:31]
**** WORKING title
CLOSED: [2020-02-15 Sat 16:31]
**** STARTED on window [1***n]
**** TODO stored [t/f]
true if tab has loadable org entry. If entry cannot be loaded disable org data editing.
*** direct actions:
**** STARTED opening a new tab
send updated state of corresponding window id to tabstore.json
**** STARTED changing a tab url
send updated state of corresponding window id to tabstore.json
**** STARTED closing a tab
send updated state of corresponding window id to tabstore.json
**** STARTED closing a window
send full updated window state to tabstore.json
**** WORKING moving tabs between windows
CLOSED: [2020-02-15 Sat 16:38]
send full updated window state to tabstore.json
**** WORKING moving a tab to a new window
CLOSED: [2020-02-15 Sat 16:38]
send full updated window state to tabstore.json
**** WORKING opening a new tab on a new window
CLOSED: [2020-02-15 Sat 16:38]
send full updated window state to tabstore.json
**** startup
***** try preference then prompt for selection
****** TODO load state from org header
****** TODO load state from existing tabstore.json
****** TODO default firefox startup
****** TODO save startup preference
*** external controls:
**** STARTED load browser state from org header
**** TODO edit org data for active tab
if (stored), load org data to populate. if not found, disable all until organize and reload.
***** edit parent
move header in org tree
****** has crosslinks
default select between crosslinks, change old parent to crosslink
****** no crosslinks
just move
***** edit title
change header text
***** edit matching
add or edit a url matching pattern to properties
****** match pattern includes current url
action edits current header
****** match pattern excludes current url
action edits current header and creates a new header for current url
******* push new header to parent
******* disable editing until queue is processed
***** edit crosslinks
add or edit additional relationships [org***brain] 
***** organize
push add/edit message onto org operation queue (edit if (stored) else add); set stored = t
***** organize and reload
organize and start queue processor. reload if queue is processed (emacs is running)
**** TODO organize all
**** TODO organize all and reload
** project state anatomy
** org anatomy
** separation
*** system
*** config
*** data & objects

